#! /bin/bash

instanceId="$1"

commands=${@:2}

cmdId=$(aws ssm send-command --instance-ids "$instanceId" --document-name "AWS-RunShellScript" --query "Command.CommandId" --output text --parameters commands="LC_CTYPE=C $commands")
[ $? -ne 0 ] && { echo "Usage: $0 instance_id command"; exit 1; }

while [ "$(aws ssm list-command-invocations --command-id "$cmdId" --query "CommandInvocations[].Status" --output text)" == "InProgress" ]; do sleep 1; done

aws ssm get-command-invocation --command-id "$cmdId" --instance-id "$instanceId" --query "StandardOutputContent" --output text
